#!/usr/bin/python

'''Membership operators in Python:(write in small case)
    1. in
    2. not in 
'''

score = 10
marks = 4

milestone = [1,2,3,4,5,6,7,8]

if(marks in milestone):
    print("You reached a mielstone")
else:
    print("No milestone so far")
